version: "3.8"
services:
    micro_01:
        build:
            args:
                user: joao
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - microservices

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8030:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservices

    # mysql
    db_micro_01:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
          - 3308:3306
        networks:
            - microservices

networks:
    microservices:
        driver: bridge

